### ISSUE TITLE
Implement Lock New Issues Workflow to Reduce Notifications ✔

### ISSUE THREAD

**Issue by Nishitbaria** [Bookingjini-Labs/bookingjini-icons#360]
### Describe the solution you'd like

```
name: 'Lock new issues'

on:
  issues:
    types: opened

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Lock issues
        uses: dessant/repo-lockdown@v3
        with:
          close-issue: false
          exclude-issue-labels: 'gssoc23.'
          process-only: 'issues'
          skip-closed-issue-comment: true
          issue-comment: >
            To reduce notifications, issues are locked. Your issue will be unlocked when we add the label `gssoc23`. If you're participating in GSSoC'23, please add the `gssoc23` label to your issue.

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
